[package]
name = "microservice_example"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "payments-server"
path = "src/server.rs"

[dependencies]
prost = "0.11.5"
tokio = { version = "1.23.0", features = ["macros", "rt-multi-thread", "signal"] }
tonic = "0.8.3"

[profile.dev]
opt-level = 0

[profile.release]
opt-level = 3
